version: '3.9'
services:
  php:
    build: .
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tutorials
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tutorials
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
    depends_on:
      - database
      - php

volumes:
  database:
